### PR TITLE
WP VIP coding standard fixes

### PR DESCRIPTION
**Pull request by PatelUtkarsh**
- Update ruleset for WordPressVIPMinimum
- Fix npm install issue
- Fix phpcs issues
- Remove deprecated features
- Remove custom table and use WP schema
- Add migration

This PR relies on https://github.com/laterpay/laterpay-client-php/pull/19

### Testing/Installation instruction for this PR

To test this PR you need to manually add composer depedency from https://github.com/rtCamp/laterpay-client-php (Default branch `feature/vip-compatible`)

Since when we run `composer install --no-dev` it will pull the previous depedenc from https://github.com/laterpay/laterpay-client-php which is no longer compatible.
Steps
- You can run `gulp` to build assets. 
- `composer install --no-dev`
- `rm -rf laterpay/vendor/laterpay/laterpay-client-php`
- `git clone --depth=1 git@github.com:rtCamp/laterpay-client-php.git laterpay/vendor/laterpay/laterpay-client-php`
- And use latepay folder as plugin.

Or use this build zip - 
https://drive.google.com/file/d/1_drtFWfiWBt9ykt91ZcIYHdmufrv0e0q/view?usp=sharing

### CODE REVIEW

**Comment by agriboed** [comment]
Hi @PatelUtkarsh 
Please check branch "feature/contributions", most of the issues were fixed.

**Comment by PatelUtkarsh** [comment]
Hey @agriboed @doismellburning

Does `feature/contributions` contains the tested code? 

Should I merge that branch in `feature/vip-compatible` or only take the changes which are required for vip?
Seems like there are many changes in file/folder structure and also it follows `PSR2` coding style.

>And what about http://php.net/manual/ru/function.filter-input.php#77307? We should provide the plugin for any webhosting.

You're right we will fix that.

**Comment by agriboed** [comment]
And look here about wp_parse_url :)
http://165.227.140.18/wp_parse_url/?test=1

**Comment by doismellburning** [comment]
@PatelUtkarsh 

> Does feature/contributions contains the tested code?

It has a combination of improved VIP support, and integration with our new Contributions API (hence the branch name). I don't know whether it's easier for you to try to pull out just the VIP changes yourself, or start from scratch from master - I think you're the best person to make that decision

> Should I merge that branch in feature/vip-compatible or only take the changes which are required for vip?

Please no, we want to focus on VIP compatibility for now; Contributions support can come later

**Comment by PatelUtkarsh** [comment]
@agriboed I've fixed that, We can add a polyfill for `wp_parse_url`. 

But we may need to add a many polyfills to support 3.5.2 and VIP coding standards together and also we were thinking to migrate table `laterpay_terms_price` to `wp_term_meta` which was also added in 4.4 and that will take some efforts.

Here is the current usage of different WordPress versions https://wordpress.org/about/stats/

@doismellburning I am not adding any changes from `feature/contributions` but there will be lot of code conflicts later on when we decide to merge these two branches.

**Comment by agriboed** [comment]
@PatelUtkarsh Ok, just check our branch - it fully supports WP 3.5.2 and PHP 5.3. As well, instead of wp_term_meta with are planned to use **wp_options** table.

**Comment by doismellburning** [comment]
@PatelUtkarsh 

>  I am not adding any changes from feature/contributions but there will be lot of code conflicts later on when we decide to merge these two branches.

I don't think we will, so that's ok!

**Comment by PatelUtkarsh** [comment]
@agriboed `wp_options` won't scale properly and likely get flagged by VIP, We are thinking to support custom table and WP schema both such that in VIP code will use WP schema and others will use the custom tables. 

As WP VIP always runs the latest version of WP we won't need to add polyfill for `wp_term_meta` related code. For other code, we can add polyfill.

**Pull request merged**
