### PR TITLE
[WIP] WordPress coding standards

### PR DESCRIPTION
**Pull request by doismellburning**
(Branches from #557 - please consider that a dependency)

### CODE REVIEW

**Comment by doismellburning** [comment]
s/let me know/update `.travis.yml` with/ cheers

**Comment by drdla** [comment]
Well. we would have to fork the WordPress standard and adjust https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress-Core/ruleset.xml#L20 to make it use four spaces.
Don't you have an opinion, how to best do that / where to put that custom config?

**Comment by doismellburning** [comment]
I'd be inclined to go for a quick fix of "just copy the file into this repo's root and hand edit".

Longer term, how about we follow the standard unmodified (i.e. with tabs)? Consistency, etc.

**Comment by drdla** [comment]
I have now forked the WordPress coding standard and tried to adjust the whitespace sniff: https://github.com/laterpay/WordPress-Coding-Standards

Given that I could not find proper documentation for phpcs rules, this should really be reviewed by somebody, e.g. @mturalenka?

**Comment by drdla** [comment]
@doismellburning please have a look at this at your earliest convenience

**Comment by doismellburning** [comment]
@drdla I'm looking, but I'm guessing you wanted me to do something else than look - sup?

**Comment by drdla** [comment]
@doismellburning no, just looking is fine. Maybe a hard stare.

**Comment by drdla** [comment]
@doismellburning I was actually wondering why the build fails, but Travis does not show me any details. I would very much like to reach the point where we can close this PR ...

**Comment by doismellburning** [comment]
@drdla If you click "Details" next to the failed status message, you end up at https://travis-ci.org/laterpay/laterpay-wordpress-plugin/builds/49723460 - scroll down to see all the errors

image

**Comment by drdla** [comment]
It never finishes loading for me:
screenshot 2015-02-10 17 09 19

**Comment by doismellburning** [comment]
Try a different browser? There are a _lot_ of errors; it does take a few moments to load...

**Pull request merged**
