### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by doismellburning**
`laterpay-client-php` is now public, so the tests mostly run

`.travis.yml` had some interesting config for running Selenium tests that are on a different branch - since it's on a different branch I've removed it - are there any non-Selenium tests, and if so, how are they run?

### CODE REVIEW

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@doismellburning As you see branch with selenium tests not merged into master. So for testing purpose previous developer used this script to run tests. He used his own ssh key, report as i see created on his own branch.

**Comment by doismellburning** [comment]
> There are no non-selenium tests.

Ah. Ok, thanks. Are there any plans to fix this, or are the selenium tests sufficiently exhaustive? Cheers

**Comment by doismellburning** [comment]
(And any idea why that branch is unmerged?)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
You mean when we plan to merge this branch into master? I don't know, most of these tests not actual anymore.

**Comment by doismellburning** [comment]
Ok, can you clarify the normal testing procedure then please?

Who knows most about the Selenium tests?

**Comment by drdla** [comment]
Quite simple: we do lots of manual testing, because the required access to the repo for running automated test was not granted.

**Comment by doismellburning** [comment]
@drdla What access is required?

**Comment by doismellburning** [comment]
(or was)

**Comment by drdla** [comment]
I can't tell you exactly. It has to do with access to the repo. Probably adding a service hook?

**Comment by doismellburning** [comment]
Who could tell me exactly...?

**Comment by drdla** [comment]
Maybe Vadim, the ScienceSoft project manager. I can hook you up on skype.

**Comment by doismellburning** [comment]
Please just get them to comment here

**Comment by VadzimBelski-ScienceSoft** [comment]
Hi , it looks pretty easy if you review it deeper
https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/.travis.yml


There are 2 secure variable in the configuration ($key_hash and $github_key_pass).

- secure: Hnmno610194Z/ZXESCE685pkyHip4GmgBKbBVZYm+zhGLW+bvEc8n6Ojfw1IteLVJahnCaZ0tgKqRebRlrhebtmWD4y+n5D80pHPZFaUHKo+ulBZ0ThxjcDfUDcXrPkgUPimP0/uwt34gy6PmJMk0tc9DmGpnJPqVIshMBCu5cc=
  - secure: m6KO5Y9+1kOks4u8Ko0isBMGYQDOYdqbWE+qfrz4/NDx17x8wqeGMN5/QiQCHgdSMRaRJuB0FDTzzQwkSg7Ea5f4UbJZgEy2224870A6jB+X7kW1CopwmdE0b4rD1nDj6BKvMr6bO7iBxmahUlego7SStJoEPlj452TQUN6KZ3Y=

More infor here http://docs.travis-ci.com/user/encryption-keys/

Key_hash - i think its ID of rsa public key for repository as far as i understand the scripting rules (this key present i think here http://54.235.193.4/tests/key.php )

github_key_pass - is actual password for this key

So follow the scripting in travis we can see the following algorithm:

- setup ssh key on 54.235.193.4 instance
- clone actual code from github for project, tests etc
- launch selenium test 
- push test report to some repository

hope this help

**Comment by doismellburning** [comment]
Thanks Vadim, but what I'm really trying to understand is when @drdla said "the required access to the repo for running automated test was not granted" / "It has to do with access to the repo. Probably adding a service hook?" - what exactly is/was needed? If I know, I can attempt to make it happen.

**Comment by VadzimBelski-ScienceSoft** [comment]
Hi ,

probably the problem is 

- access to the repo of plugin
- access to the repo of selenium tests https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/.travis.yml#L21 (see this like)

As far as i know Selenium tests not included in Laterpay Worpdress public repo - so travis require credentials to fetch sources. I do not see other issues.

**Comment by doismellburning** [comment]
Thanks Vadim.

> access to the repo of plugin

That's this repo, right? This repo's public

> access to the repo of selenium tests https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/.travis.yml#L21 (see this like)

```
L21: git clone -b feature/selenium-tests git@github.com:laterpay/laterpay-wordpress-plugin.git
```

That's also this repo, just a different branch (though, among other things, it probably should be using https to be able to clone anonymously, which I suspect was the immediate issue)

Higher level though, generally, if your tests on branch X require code from branch Y, there's something nasty going on.

What almost certainly should happen is that the tests get merged into mainline, thus 99% of that logic in `.travis.yml` goes away, and it just becomes (effectively) `cd selenium_tests && ./run`.

I recommend we merge this branch into master - it takes master's tests from "not running at all on travis because they fail at an early step" to "passing, but because they do nothing", which, while not much of an improvement, still _is_ an improvement. **Then** we fix the `feature/selenium-tests` branch, and get that merged in.

How does that sound?

**Comment by VadzimBelski-ScienceSoft** [comment]
Looks ok

**Comment by doismellburning** [comment]
@VadzimBelski-ScienceSoft In which case, please merge this, thanks

**Comment by doismellburning** [comment]
(Or anyone please; doesn't need to be Vadzim!)

**Comment by doismellburning** [comment]
Cheers

**Pull request merged**
