### PR TITLE
Feature/10 fix styling of editing category prices

### PR DESCRIPTION
**Pull request by drdla**

### CODE REVIEW

**Comment by twoldrich** [comment]
When the WordPress language is **German**, prices are not displayed correctly:

**Example:**
- Go to the pricing tab
- Edit the global default price to **0,2** => It is correctly changed to **0,20**.
- Save the global default price => It is changed to **2,00**.

After changing the WordPress language to **English**, everything works fine.

**Comment by twoldrich** [comment]
The button for a revenue model that is currently not available ("PPU" in the screenshot) still has a blue hover effect. 

image

**Comment by drdla** [comment]
Could not reproduce
> When the WordPress language is German, prices are not displayed correctly:

**Comment by twoldrich** [comment]
Otherwise, everything works fine for me!

**Comment by twoldrich** [comment]
For a new category default price, the global default price is used initially. When the **global default price** uses the revenue model **SIS**, still **PPU** is selected for a new category default price.

image

**Comment by drdla** [comment]
Can't reproduce.

**Pull request merged**
