### PR TITLE
[WIP] Selenium tests

### PR DESCRIPTION
**Pull request by doismellburning**

### CODE REVIEW

**Comment by doismellburning** [comment]
Going to see if I can get these running / merged...

**Comment by doismellburning** [comment]
I started this PR...some time ago now, to unify the two branches. Frankly I'm not sure of the state of it nowadays (you'll observe that most of the commits aren't mine!)

@AliaksandrVahura-ScienceSoft As the person with the most recent commits here, what's your view/opinions?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Last changes were made according to the ticket #769 where you can find information about current state of tests. It seems readme not actual anymore.

**Comment by doismellburning** [comment]
I'm going to close this PR, but keep the branch so it doesn't get GC-ed; I think there's value in these commits, but it's not particularly easily extractable - thanks!

**Pull request closed without merging**
