### PR TITLE
Automatically run JSHint

### PR DESCRIPTION
**Pull request by doismellburning**

### CODE REVIEW

**Comment by doismellburning** [comment]
@drdla Can I leave the task of fixing these errors in your hands please?

**Comment by drdla** [comment]
Which errors? LPCurve is not defined?

**Comment by doismellburning** [comment]
All of the errors that mean the build fails - https://travis-ci.org/laterpay/laterpay-wordpress-plugin/builds/48471824 (the "Details" link on the build status)

**Comment by drdla** [comment]
@doismellburning I resolved most errors with the help of @StefanKjartansson, but could not make those go away:
````
laterpay/asset_sources/js/d3.dynamic.widget.js: line 10, col 5, Redefinition of 'LPCurve'.
laterpay/asset_sources/js/laterpay-backend.js: line 5, col 10, 'setMessage' is defined but never used.
```
Can you or someone else help?

**Comment by doismellburning** [comment]
Thanks. I'm afraid I don't really speak JS, but does the second not just mean you can delete `setMessage` as it's unused...?

**Pull request merged**
