### PR TITLE
Automatically run JSHint

### PR DESCRIPTION
**Pull request by doismellburning**
(Depends on #557)

### CODE REVIEW

**Comment by drdla** [comment]
@doismellburning I could not find any reference so I am asking you: will Travis run the JSHint configuration we are already using (https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/.jshintrc) or will it use another one?

**Comment by doismellburning** [comment]
Should be the former; do you have reason to believe it's not...?

**Comment by drdla** [comment]
No I don't. I was just expecting to see some kind of path to the jshintrc in the changes, but failed to find one.

**Comment by doismellburning** [comment]
I'd just got master passing too :(

Please please please can you not merge PRs with failing tests.

The PR was open because the tests fail because although the README says "must pass jshint" the tests would seem to show that that doesn't hold for current code...

**Pull request merged**
